VnuaVaccine/Controllers/CartController.cs
using DAL.Dao;
using DAL.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VnuaVaccine.Common;
using VnuaVaccine.Models;
using static System.Collections.Specialized.BitVector32;

namespace VnuaVaccine.Controllers
{
    public class CartController : Controller
    {
        private const string CartSession = "CartSession";
        private readonly ScheduleDAO _scheduleDao = new ScheduleDAO();
        public ActionResult Index()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }

            return View(list);
        }

        public ActionResult AddToCart(int idVaccine, int quantity)
        {
            #region check login

            var userDao = new UserDAO();
            var userLogin = (UserLogin)Session[SessionConstants.USER_SESSION];
            if (userLogin == null)
            {
                return RedirectToAction("Index", "Login", new { area = "Admin" });
            }

            var user = userDao.GetById(userLogin.UserID);
            if (user == null)
            {
                return RedirectToAction("Index", "Login", new { area = "Admin" });
            }
            #endregion

            #region addtocart                              

            try
            {
                int loggedInUserId = userLogin.UserID;
                var userNameId = _scheduleDao.GetUserNameId(loggedInUserId);

                var vaccine = new VaccineDAO().ViewDetail(idVaccine);
                var cart = Session[CartSession];
                if (cart != null)
                {
                    var list = (List<CartItem>)cart;
                    if (list.Exists(x => x.Vaccine.ID == idVaccine))
                    {
                        foreach (var item in list)
                        {
                            if (item.Vaccine.ID == idVaccine)
                            {
                                item.Quantity += quantity;
                            }
                        }
                    }
                    else
                    {
                        var item = new CartItem();
                        item.IdPatient = userNameId;
                        item.Vaccine = vaccine;
                        item.Quantity = quantity;
                        item.Status = 0;
                        item.CreateAt = DateTime.Now;
                        list.Add(item);
                    }
                    Session[CartSession] = list;
                }
                else
                {
                    var item = new CartItem();
                    item.IdPatient = userNameId;
                    item.Vaccine = vaccine;
                    item.Quantity = quantity;
                    item.CreateAt = DateTime.Now;
                    item.Status = 0;
                    var list = new List<CartItem>();
                    list.Add(item);
                    Session[CartSession] = list;
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Đã có lỗi xảy ra, vui lòng thử lại sau!");
                return View("Index");
            }
            #endregion
        }

        public ActionResult RemoveFromCart(int id)
        {
            try
            {
                var cart = (List<CartItem>)Session[CartSession];
                if (cart != null)
                {
                    var item = cart.FirstOrDefault(i => i.ID == id);
                    if (item != null)
                    {
                        cart.Remove(item);
                    }
                }
                Session[CartSession] = cart;
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Đã có lỗi xảy ra, vui lòng thử lại sau!");
                return View("Index");
            }

        }

        public ActionResult SaveSchedule()
        {
            try
            {
                var cart = (List<CartItem>)Session[CartSession];
                if (cart != null && cart.Count > 0)
                {
                    var vaccineScheduleDao = new ScheduleDAO();

                    foreach (var cartItem in cart)
                    {
                        var schedule = new VaccinationSchedule
                        {
                            Quantity = cartItem.Quantity,
                            IdPatient = cartItem.IdPatient,
                            IdVaccine = cartItem.Vaccine.ID,
                            Status = 0,
                            CreateAt = DateTime.Now,
                        };
                        vaccineScheduleDao.Insert(schedule);
                    }

                    Session[CartSession] = null;
                }
                else
                {
                    ModelState.AddModelError("", "Giỏ hàng trống. Vui lòng thêm mục hàng trước khi lưu lịch tiêm chủng.");
                    return View("Index");
                }

                return RedirectToAction("SaveSuccess");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Đã có lỗi xảy ra, vui lòng thử lại sau!");
                return View("Index");
            }
        }

        public ActionResult SaveSuccess()
        {
            return View();
        }
    }
}

VnuaVaccine/Controllers/ListVaccineController.cs
using DAL.Dao;
using System;
using System.Web.Mvc;

namespace VnuaVaccine.Controllers
{
    public class ListVaccineController : Controller
    {
        // GET: ListVaccine
        public ActionResult Index(string searchString, int page = 1, int pageSize = 6)
        {
            try
            {
                var productDao = new VaccineDAO();
                var model = productDao.ListAllPaging(searchString, page, pageSize);

                ViewBag.SearchString = searchString;
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        public ActionResult Detail(int id)
        {
            try
            {
                var vaccineDAO = new VaccineDAO();
                var vaccine = vaccineDAO.ViewDetail(id);
                if (vaccine == null)
                {
                    return RedirectToAction("Index");
                }
                return View(vaccine);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

VnuaVaccine/Views/Cart/Index.cshtml
@model List<VnuaVaccine.Models.CartItem>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section navlink {
    <li class="nav-item">
        <a class="nav-link active" href="~/Home/Index" onclick="changeColor(this)">Trang chủ</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="~/Home/About" onclick="changeColor(this)">Về chúng tôi</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="~/ListVaccine/Index" onclick="changeColor(this)">Vaccine</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/Admin/Wishlist/Index" onclick="changeColor(this)">Lịch sử tiêm</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#section-form" onclick="changeColor(this)">Liên hệ</a>
    </li>
    <script>
        function changeColor(link) {

            var links = document.querySelectorAll('.nav-link');
            // Loại bỏ class active
            links.forEach(function (link) {
                link.classList.remove('active');
            });
            // Thêm class active vào phần tử được chọn
            link.classList.add('active');
        }
    </script>
}

@section body1{
    @using (Html.BeginForm("Save", "Cart", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="card-header py-3">
            <h2 class="m-0 font-weight-bold text-primary" style="text-align:center;">Cart</h2>
        </div>
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <table style="text-align:center" class="table table-striped table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Ảnh</th>
                            <th>Tên Vaccine</th>
                            <th>Số lượng</th>
                            <th>Ngày đặt</th>
                            <th></th>
                        </tr>
                    </thead>
                    @{
                        int idCounter = 1;
                    }
                    <tbody>
                        @if (Model.Count == 0)
                        {
                            <tr>
                                <td colspan="9" class="text-center">Không có lịch tiêm</td>
                            </tr>
                        }
                        @if (Model.Count != 0)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@idCounter</td>
                                    <td> <img src="@item.Vaccine.Path" width="50" /></td>
                                    <td>@item.Vaccine.NameVaccine</td>
                                    <td><input type="text" value="@item.Quantity" /></td>
                                    <td>@(item.CreateAt == null ? "" : item.CreateAt.Value.ToString("dd/MM/yyyy"))</td>
                                    <td>
                                        <a style="text-decoration: none;" href="@Url.Action("RemoveFromCart", "Cart",
                                                                                               new { id = item.ID })" class="btn btn-danger" onclick="return confirm('Xác nhận xoá?')">
                                            <i class="fas fa-trash"></i> Xoá
                                        </a>
                                    </td>
                                </tr>

                                idCounter++;
                            }
                        }
                </table>
            </div>
        </div>

    }
    <div class="row">
        <div class="col-md-2">
            <a class="btn btn-primary btn-user btn-block icon" href="@Url.Action("Index", "ListVaccine")">
                Quay lại
            </a>
        </div>
        <div class="col-md-8"></div>
        <div class="col-md-2">
            <a class="btn btn-info btn-user btn-block icon" href="@Url.Action("SaveSchedule", "Cart")">
                Đặt lịch
            </a>
        </div>
    </div>

}

VnuaVaccine/Views/Cart/SaveSuccess.cshtml
@{
    ViewBag.Title = "SaveSuccess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section navlink {
    <li class="nav-item">
        <a class="nav-link active" href="~/Home/Index" onclick="changeColor(this)">Trang chủ</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="~/Home/About" onclick="changeColor(this)">Về chúng tôi</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="~/ListVaccine/Index" onclick="changeColor(this)">Vaccine</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#" onclick="changeColor(this)">Tin tức</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#section-form" onclick="changeColor(this)">Liên hệ</a>
    </li>
    <script>
        function changeColor(link) {

            var links = document.querySelectorAll('.nav-link');
            // Loại bỏ class active
            links.forEach(function (link) {
                link.classList.remove('active');
            });
            // Thêm class active vào phần tử được chọn
            link.classList.add('active');
        }
    </script>
}

@section body{
    <div class="vh-100 d-flex justify-content-center align-items-center">
        <div class="col-md-6">
            <div class="border border-4 border-primary"></div>
            <div class="card  bg-white shadow p-5">
                <div class="mb-4 text-center">
                    <svg xmlns="http://www.w3.org/2000/svg" class="text-primary bi bi-check-circle" width="75" height="75"
                         fill="currentColor" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                        <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z" />
                    </svg>
                </div>
                <div class="text-center">
                    <h1>Cảm ơn bạn!</h1>
                    <p>Chúng tôi đã nhận được yêu cầu đặt lịch tiêm từ bạn. Vui lòng chờ thông báo trong email! </p>


                    <button class="btn btn-primary" onclick="window.location.href='/Admin/Wishlist/Index'">Xem lịch tiêm</button>
                </div>
            </div>
        </div>
    </div>
}
@section form{
    <h1 class="text-center wow fadeInUp">Để Lại Lời Nhắn Cho Bác Sĩ</h1>

    <form class="main-form">
        <div class="row mt-5 ">
            <div class="col-12 col-sm-6 py-2 wow fadeInLeft">
                <input type="text" class="form-control" placeholder="Tên đầy đủ">
            </div>
            <div class="col-12 col-sm-6 py-2 wow fadeInRight">
                <input type="text" class="form-control" placeholder="Địa chỉ email..">
            </div>
            <div class="col-12 col-sm-6 py-2 wow fadeInLeft" data-wow-delay="300ms">
                <input type="date" class="form-control">
            </div>
            <div class="col-12 col-sm-6 py-2 wow fadeInRight" data-wow-delay="300ms">
                <select name="departement" id="departement" class="custom-select">
                    <option value="general">Tình Trạng Sức Khoẻ</option>
                    <option value="cardiology">Tốt</option>
                    <option value="dental">Bình Thường</option>
                    <option value="neurology">Xấu</option>
                </select>
            </div>
            <div class="col-12 py-2 wow fadeInUp" data-wow-delay="300ms">
                <input type="text" class="form-control" placeholder="Số điện thoại">
            </div>
            <div class="col-12 py-2 wow fadeInUp" data-wow-delay="300ms">
                <textarea name="message" id="message" class="form-control" rows="6" placeholder="Lời nhắn.."></textarea>
            </div>
        </div>

        <button type="submit" class="btn btn-primary mt-3 wow zoomIn">Gửi yêu cầu</button>
    </form>
}